#!/bin/sh
set -e

. /usr/share/debconf/confmodule

# Configuration
db_get resolver/base_url
base_url="$RET"
secret_key=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
salt=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

# Database
dbc_generate_include_args "-o template_infile=/etc/resolver/resolver.cfg.example"
dbc_generate_include template:/etc/resolver/resolver.cfg

# Gunicorn
sed	-e s/__BASE_URL__/$base_url/ \
	-e s/__SECRET_KEY__/$secret_key/ \
	-e s/__SALT__/$salt/ </etc/resolver/resolver.cfg >/etc/resolver/resolver.cfg 

# Apache config
db_get resolver/server_name
server_name="$RET"
sed	-e s/__SERVER_NAME__/$server_name/ </etc/apache2/sites-available/resolver.conf >/etc/apache2/sites-available/resolver.conf

a2ensite resolver.conf
service apache2 reload

# Supervisor
supervisorctl reread
supervisorctl update
